semi: false
singleQuote: true
trailingComma: es5
printWidth: 100
tabWidth: 2
objectWrap: collapse
proseWrap: always

plugins:
  - prettier-plugin-astro
overrides:
  - files: '*.astro'
    options:
      parser: astro
